name: C/C++ / Check everything builds & tests

on:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        working-directory: ${{github.workspace}}/bindings/c
        run: cmake -B build -DSAFETENSORS_BUILD_TESTS=ON

      - name: Build
        working-directory: ${{github.workspace}}/bindings/c/build/
        run: cmake --build --target safetensors_tests --parallel

      - name: Test
        working-directory: ${{github.workspace}}/bindings/c/build
        run: ctest tests
